# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extendPeak.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(174, 67)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox.setMaximum(9999.99)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.pushButton_OK = QtWidgets.QPushButton(Dialog)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_OK)
        self.pushButton_Cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_Cancel.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_Cancel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "额外检测峰"))
        self.label.setText(_translate("Dialog", "添加额外峰："))
        self.doubleSpinBox.setSuffix(_translate("Dialog", "nm"))
        self.pushButton_OK.setText(_translate("Dialog", "确定"))
        self.pushButton_Cancel.setText(_translate("Dialog", "取消"))
