# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(959, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OpenCommBtn = QtWidgets.QPushButton(self.tab)
        self.OpenCommBtn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.OpenCommBtn.setObjectName("OpenCommBtn")
        self.verticalLayout_2.addWidget(self.OpenCommBtn)
        self.CloseCommBtn = QtWidgets.QPushButton(self.tab)
        self.CloseCommBtn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.CloseCommBtn.setObjectName("CloseCommBtn")
        self.verticalLayout_2.addWidget(self.CloseCommBtn)
        self.VersionBtn = QtWidgets.QPushButton(self.tab)
        self.VersionBtn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.VersionBtn.setObjectName("VersionBtn")
        self.verticalLayout_2.addWidget(self.VersionBtn)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.IntTimeEdt = QtWidgets.QLineEdit(self.groupBox)
        self.IntTimeEdt.setObjectName("IntTimeEdt")
        self.verticalLayout.addWidget(self.IntTimeEdt)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.NumAvgEdt = QtWidgets.QLineEdit(self.groupBox)
        self.NumAvgEdt.setObjectName("NumAvgEdt")
        self.verticalLayout.addWidget(self.NumAvgEdt)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.NumMeasEdt = QtWidgets.QLineEdit(self.groupBox)
        self.NumMeasEdt.setObjectName("NumMeasEdt")
        self.verticalLayout.addWidget(self.NumMeasEdt)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.StartMeasBtn = QtWidgets.QPushButton(self.tab)
        self.StartMeasBtn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.StartMeasBtn.setObjectName("StartMeasBtn")
        self.verticalLayout_2.addWidget(self.StartMeasBtn)
        self.StopMeasBtn = QtWidgets.QPushButton(self.tab)
        self.StopMeasBtn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.StopMeasBtn.setObjectName("StopMeasBtn")
        self.verticalLayout_2.addWidget(self.StopMeasBtn)
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.plot = RenderArea(self.tab)
        self.plot.setMinimumSize(QtCore.QSize(600, 600))
        self.plot.setObjectName("plot")
        self.horizontalLayout.addWidget(self.plot)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_asdInput = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_asdInput.setObjectName("pushButton_asdInput")
        self.horizontalLayout_3.addWidget(self.pushButton_asdInput)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.pushButton_asdColor = ColorButton(self.groupBox_2)
        self.pushButton_asdColor.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_asdColor.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_asdColor.setText("")
        self.pushButton_asdColor.setObjectName("pushButton_asdColor")
        self.horizontalLayout_3.addWidget(self.pushButton_asdColor)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.checkBox_asdShow = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_asdShow.setChecked(True)
        self.checkBox_asdShow.setObjectName("checkBox_asdShow")
        self.horizontalLayout_3.addWidget(self.checkBox_asdShow)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.horizontalSlider_asdTranslate = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_asdTranslate.setMinimum(-300)
        self.horizontalSlider_asdTranslate.setMaximum(300)
        self.horizontalSlider_asdTranslate.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_asdTranslate.setObjectName("horizontalSlider_asdTranslate")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_asdTranslate)
        self.doubleSpinBox_asdTranslate = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_asdTranslate.setPrefix("")
        self.doubleSpinBox_asdTranslate.setMinimum(-3.0)
        self.doubleSpinBox_asdTranslate.setMaximum(3.0)
        self.doubleSpinBox_asdTranslate.setSingleStep(0.01)
        self.doubleSpinBox_asdTranslate.setObjectName("doubleSpinBox_asdTranslate")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_asdTranslate)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.doubleSpinBox_asdThreshold = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_asdThreshold.setSuffix("")
        self.doubleSpinBox_asdThreshold.setDecimals(4)
        self.doubleSpinBox_asdThreshold.setMaximum(1.0)
        self.doubleSpinBox_asdThreshold.setSingleStep(0.0001)
        self.doubleSpinBox_asdThreshold.setObjectName("doubleSpinBox_asdThreshold")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_asdThreshold)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.doubleSpinBox_asdDamping = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_asdDamping.setDecimals(3)
        self.doubleSpinBox_asdDamping.setMinimum(0.001)
        self.doubleSpinBox_asdDamping.setMaximum(10.0)
        self.doubleSpinBox_asdDamping.setSingleStep(0.01)
        self.doubleSpinBox_asdDamping.setProperty("value", 0.1)
        self.doubleSpinBox_asdDamping.setObjectName("doubleSpinBox_asdDamping")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_asdDamping)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_measureInput = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_measureInput.setObjectName("pushButton_measureInput")
        self.horizontalLayout_6.addWidget(self.pushButton_measureInput)
        self.line_4 = QtWidgets.QFrame(self.groupBox_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.pushButton_mearsureColor = ColorButton(self.groupBox_3)
        self.pushButton_mearsureColor.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_mearsureColor.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_mearsureColor.setText("")
        self.pushButton_mearsureColor.setObjectName("pushButton_mearsureColor")
        self.horizontalLayout_6.addWidget(self.pushButton_mearsureColor)
        self.line_5 = QtWidgets.QFrame(self.groupBox_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_6.addWidget(self.line_5)
        self.checkBox_mearsureShow = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_mearsureShow.setChecked(True)
        self.checkBox_mearsureShow.setObjectName("checkBox_mearsureShow")
        self.horizontalLayout_6.addWidget(self.checkBox_mearsureShow)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.horizontalSlider_measureTranslate = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider_measureTranslate.setMinimum(-300)
        self.horizontalSlider_measureTranslate.setMaximum(300)
        self.horizontalSlider_measureTranslate.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_measureTranslate.setObjectName("horizontalSlider_measureTranslate")
        self.horizontalLayout_7.addWidget(self.horizontalSlider_measureTranslate)
        self.doubleSpinBox_measureTranslate = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_measureTranslate.setPrefix("")
        self.doubleSpinBox_measureTranslate.setMinimum(-3.0)
        self.doubleSpinBox_measureTranslate.setMaximum(3.0)
        self.doubleSpinBox_measureTranslate.setSingleStep(0.01)
        self.doubleSpinBox_measureTranslate.setObjectName("doubleSpinBox_measureTranslate")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_measureTranslate)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.doubleSpinBox_measureThreshold = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_measureThreshold.setSuffix("")
        self.doubleSpinBox_measureThreshold.setDecimals(4)
        self.doubleSpinBox_measureThreshold.setMaximum(1.0)
        self.doubleSpinBox_measureThreshold.setSingleStep(0.0001)
        self.doubleSpinBox_measureThreshold.setObjectName("doubleSpinBox_measureThreshold")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_measureThreshold)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.doubleSpinBox_measureSmothingFactor = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_measureSmothingFactor.setDecimals(2)
        self.doubleSpinBox_measureSmothingFactor.setMinimum(0.0)
        self.doubleSpinBox_measureSmothingFactor.setMaximum(1.0)
        self.doubleSpinBox_measureSmothingFactor.setSingleStep(0.1)
        self.doubleSpinBox_measureSmothingFactor.setProperty("value", 0.6)
        self.doubleSpinBox_measureSmothingFactor.setObjectName("doubleSpinBox_measureSmothingFactor")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_measureSmothingFactor)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.doubleSpinBox_zoomUp = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_zoomUp.setMaximum(9999.0)
        self.doubleSpinBox_zoomUp.setObjectName("doubleSpinBox_zoomUp")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_zoomUp)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.doubleSpinBox_zoomDown = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_zoomDown.setMaximum(9999.0)
        self.doubleSpinBox_zoomDown.setObjectName("doubleSpinBox_zoomDown")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_zoomDown)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.checkBox_showCharacteristicPeak = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_showCharacteristicPeak.setObjectName("checkBox_showCharacteristicPeak")
        self.verticalLayout_7.addWidget(self.checkBox_showCharacteristicPeak)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.doubleSpinBox_peakThreshold = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_peakThreshold.setSuffix("")
        self.doubleSpinBox_peakThreshold.setDecimals(4)
        self.doubleSpinBox_peakThreshold.setMaximum(1.0)
        self.doubleSpinBox_peakThreshold.setSingleStep(0.0001)
        self.doubleSpinBox_peakThreshold.setProperty("value", 0.0001)
        self.doubleSpinBox_peakThreshold.setObjectName("doubleSpinBox_peakThreshold")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_peakThreshold)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget_peak = peakTableWidget(self.groupBox_5)
        self.tableWidget_peak.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tableWidget_peak.setObjectName("tableWidget_peak")
        self.tableWidget_peak.setColumnCount(3)
        self.tableWidget_peak.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_peak.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_peak.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_peak.setHorizontalHeaderItem(2, item)
        self.verticalLayout_8.addWidget(self.tableWidget_peak)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.plot_offline = GraphicsLayoutWidget(self.tab_2)
        self.plot_offline.setMinimumSize(QtCore.QSize(600, 400))
        self.plot_offline.setObjectName("plot_offline")
        self.horizontalLayout_2.addWidget(self.plot_offline)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.OpenCommBtn, self.CloseCommBtn)
        MainWindow.setTabOrder(self.CloseCommBtn, self.VersionBtn)
        MainWindow.setTabOrder(self.VersionBtn, self.IntTimeEdt)
        MainWindow.setTabOrder(self.IntTimeEdt, self.NumAvgEdt)
        MainWindow.setTabOrder(self.NumAvgEdt, self.NumMeasEdt)
        MainWindow.setTabOrder(self.NumMeasEdt, self.StartMeasBtn)
        MainWindow.setTabOrder(self.StartMeasBtn, self.StopMeasBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OpenCommBtn.setText(_translate("MainWindow", "Open Communication"))
        self.CloseCommBtn.setText(_translate("MainWindow", "Close Communication"))
        self.VersionBtn.setText(_translate("MainWindow", "Show Version Info"))
        self.groupBox.setTitle(_translate("MainWindow", "Measurement Parameters"))
        self.label.setText(_translate("MainWindow", "Integration Time [ms]"))
        self.label_2.setText(_translate("MainWindow", "Number of Averages"))
        self.label_3.setText(_translate("MainWindow", "Number of Measurements"))
        self.StartMeasBtn.setText(_translate("MainWindow", "Start Measurements"))
        self.StopMeasBtn.setText(_translate("MainWindow", "Stop Measurements"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "onlineModel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "ASD data"))
        self.pushButton_asdInput.setText(_translate("MainWindow", "openFile"))
        self.label_4.setText(_translate("MainWindow", "color:"))
        self.checkBox_asdShow.setText(_translate("MainWindow", "show"))
        self.label_5.setText(_translate("MainWindow", "Translate："))
        self.doubleSpinBox_asdTranslate.setSuffix(_translate("MainWindow", "nm"))
        self.label_6.setText(_translate("MainWindow", "threshold:"))
        self.label_13.setText(_translate("MainWindow", "damping:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "measured data"))
        self.pushButton_measureInput.setText(_translate("MainWindow", "openFile"))
        self.label_7.setText(_translate("MainWindow", "color:"))
        self.checkBox_mearsureShow.setText(_translate("MainWindow", "show"))
        self.label_8.setText(_translate("MainWindow", "Translate："))
        self.doubleSpinBox_measureTranslate.setSuffix(_translate("MainWindow", "nm"))
        self.label_9.setText(_translate("MainWindow", "threshold:"))
        self.label_14.setText(_translate("MainWindow", "smoothing factor:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "tools"))
        self.label_10.setText(_translate("MainWindow", "zoom range"))
        self.label_11.setText(_translate("MainWindow", "--"))
        self.checkBox_showCharacteristicPeak.setText(_translate("MainWindow", "show characteristic peak"))
        self.label_12.setText(_translate("MainWindow", "peak threshold:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "characteristic peak and peak area"))
        item = self.tableWidget_peak.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "peak label"))
        item = self.tableWidget_peak.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "peak position"))
        item = self.tableWidget_peak.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "relative peak area"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "offlineModel"))

from dependent.myWidget import peakTableWidget
from dependent.renderarea import RenderArea
from pyqtgraph import ColorButton, GraphicsLayoutWidget
